Frontend Structure and Setup
SpiffiRacoon/ISBiT pull request #21
Opened 2024-10-01 17:30 UTC by LinusHakegard

Folder Structure: Established a basic folder structure for the project.

Navbar: Added a simple, functional navigation bar component.

Dataset Selection Page: Implemented a basic dataset selection page where objects are currently hard-coded. Backend communication is being developed in another branch.

Docker Setup: Dockerized the application and included it in the Docker Compose file.

2024-10-01 20:58 UTC, Sinoeng approved these changes
Ser ut som en bra början :)

2024-10-02 07:42 UTC, Leohemmingsson requested changes
Ser bra ut allt som allt, jag la in ett ändringsförslag för att fixa routingen bara.

2024-10-03 14:39 UTC, LinusHakegard commented on Frontend/isbit/Dockerfile
> +CMD [ "http-server", "dist" ]
Yes, snygg find

2024-10-03 15:42 UTC, Leohemmingsson approved these changes

2024-10-03 15:43 UTC, merged