Added routes to see dim and model, also makde models more dynamic
SpiffiRacoon/ISBiT pull request #84
Opened 2024-11-24 14:03 UTC by Leohemmingsson

# Description
Creating routes to get dimension reductions as well as models.

# Additional features/fixes
* Made the models dynamic
* Fixed small variable name bug in manual test
* Removed faulty requests in frontend
* Added default values in swagger for the run_ml route
* Removed some debugging prints

# Good to know
* The route to run_ml now takes a new name to run qaqc_main => QaqcMainModel. The names are based on what the models are called.
* Frontend has been tested, and everything *should* work as before

Closes #78

2024-11-24 15:53 UTC, Varlog22 approved these changes
Everything looks in order and the code runs, LGTM

2024-11-25 20:19 UTC, SpiffiRacoon requested changes

2024-11-26 06:44 UTC, Leohemmingsson commented on Backend/src/ml_lib/factory/getter.py
> +import inspect
Done

2024-11-26 06:46 UTC, SpiffiRacoon approved these changes
Nice, LGTM :)

2024-11-26 06:47 UTC, merged